title: "&bOre Processor | Menu"
layout:
  - "---------"
  - "--XXXXX--"
  - "--XXXXX--"
  - "---------"
components:
  "-":
    name: "&e"
    material: gray_stained_glass_pane
  "X":
    type: ore
    name: "&e"
    material: black_stained_glass_pane
ore-lore:
 - "&7▪ In queue: {queue}"
 - "&7▪ In storage: {storage-current}/{storage-capacity}"
 - "&7▪ Throughput: {throughput}/m"
 - ""
 - "&e» Left-click to open storage."
 - "&e» Right-click to upgrade."