title: "&0Ore Processor | Storage"
layout:
  - "---------"
  - "--X--IO--"
  - "---------"
  - "++++|++++"
components:
  "-":
    name: "&e"
    material: gray_stained_glass_pane
  "+":
    name: "&e"
    material: black_stained_glass_pane
  "X":
    type: ore
    material: gray_stained_glass_pane
    name: "&b{ore} &f({storage-ratio}%)"
    lore:
      - "&7▪ Processing: {processing}"
      - "&7▪ In storage: {storage-current}/{storage-capacity}"
      - "&7▪ Throughput: {throughput}/m"
      - ""
      - "&e» Click to upgrade."
  "I":
    type: input
    material: hopper
    name: "&aStore {ore}"
    lore:
      - "&7▪ Amount: {current}/{capacity}"
      - ""
      - "&e» Drop {ore} into the hopper to store."
  "O":
    type: output
    material: chest
    name: "&aTake {ore}"
    lore:
      - "&7▪ Amount: {current}/{capacity}"
      - ""
      - "&fLeft:       &eTake x1 {ore}"
      - "&fRight:      &eTake x64 {ore}"
      - "&fLeft+Shift:  &eTake x16 {ore}"
      - "&fRight+Shift: &eTake x32 {ore}"
  "|":
    type: back
    material: barrier
    name: "&cBack"
    lore:
      - "&e» Go back to main menu"
