title: "&0Ore Processor | Upgrade"
layout:
  - "---------"
  - "--T---C--"
  - "---------"
  - "++++|++++"
components:
  "-":
    name: "&e"
    material: gray_stained_glass_pane
  "+":
    name: "&e"
    material: black_stained_glass_pane
  "T":
    type: throughput
    material: hopper
    name: "&dUpgrade throughput"
  "C":
    type: capacity
    material: chest
    name: "&dUpgrade capacity"
  "|":
    type: back
    material: barrier
    name: "&cBack"
    lore:
      - "&e» Go back to main menu"

throughput-upgradable-lore:
  - "&fIncrease processing rate to obtain {ore} faster."
  - ""
  - "&7▪ Current: {current-throughput}/m"
  - "&7▪ Next level: {next-throughput}/m"
  - "&7▪ Upgrade cost: ${cost}"
  - ""
  - "&e» Click to confirm upgrade."

throughput-unaffordable-lore:
  - "&fIncrease processing rate to obtain {ore} faster."
  - ""
  - "&7▪ Current: {current-throughput}/m"
  - "&7▪ Next level: {next-throughput}/m"
  - "&7▪ Upgrade cost: ${cost}"
  - ""
  - "&c[Not enough balance]"

throughput-maximized-lore:
  - "&fIncrease processing rate to obtain {ore} faster."
  - ""
  - "&7▪ Current: {current-throughput}/m"
  - ""
  - "&c[Maximum level reached]"

capacity-upgradable-lore:
  - "&fIncrease {ore} storage capacity."
  - ""
  - "&7▪ Current: {current-capacity}"
  - "&7▪ Next level: {next-capacity}"
  - "&7▪ Upgrade cost: ${cost}"
  - ""
  - "&e» Click to confirm upgrade."

capacity-unaffordable-lore:
  - "&fIncrease {ore} storage capacity."
  - ""
  - "&7▪ Current: {current-capacity}"
  - "&7▪ Next level: {next-capacity}"
  - "&7▪ Upgrade cost: ${cost}"
  - ""
  - "&c[Not enough balance]"

capacity-maximized-lore:
  - "&fIncrease {ore} storage capacity."
  - ""
  - "&7▪ Current: {current-capacity}"
  - ""
  - "&c[Maximum level reached]"
